---
services:
  jellysweep:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: jellysweep
    volumes:
      # cache for images
      - ./data:/app/data
      - ./config_env.yml:/app/config.yml
      # - ./config.yml:/app/config.yml
    network_mode: host
    # networks:
    #   default:
    environment:
      TZ: Europe/Zurich
    env_file:
      - .env.dev

  # valkey:
  #   image: valkey/valkey:8-bookworm
  #   container_name: jellysweep-valkey
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     default:

networks:
  default:
