---
services:
  jellysweep:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: jellysweep
    volumes:
      # cache for images
      - ./data:/app/data
      # - ./config.yml:/app/config.yml
    networks:
      default:
    environment:
      TZ: Europe/Zurich
      JELLYSWEEP_CACHE_TYPE: redis
      JELLYSWEEP_CACHE_REDIS_URL: valkey:6379
    env_file:
      - .env.dev

  valkey:
    image: valkey/valkey:8-bookworm
    container_name: jellysweep-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      default:

networks:
  default:
