site_name = "Jellysweep"
site_url = "https://jon4hz.github.io/jellysweep/"
repo_url = "https://github.com/jon4hz/jellysweep"
extra_css = [ "stylesheets/extra.css" ]
plugins = [ "search" ]
edit_uri = "edit/main/docs/"
copyright = "Copyright &copy; 2025 - 2026 The Jellysweep Contributors"

nav = [
  {"Home" = "index.md"},
  {"How it works: Filters" = "how-it-works-filters.md"},
  {"Installation Guide" = "installation.md"},
  {"Troubleshooting" = "troubleshooting.md"},
]

[theme]
name = "material"
logo = "assets/jellysweep.png"
favicon = "assets/jellysweep.png"
features = [
  "content.action.edit",
  "navigation.footer",
  "search.share",
  "search.suggest"
]

  [theme.icon]
  repo = "fontawesome/brands/github"
  edit = "material/pencil"
  view = "material/eye"

  [theme.palette]
  scheme = "slate"
  primary = "custom"
  accent = "custom"

  [theme.font]
  text = "Inter"
  code = "Roboto Mono"

[extra]
generator = false

  [[extra.social]]
  icon = "fontawesome/brands/github"
  link = "https://github.com/jon4hz/jellysweep"

  [[extra.social]]
  icon = "fontawesome/brands/docker"
  link = "https://github.com/jon4hz/jellysweep/pkgs/container/jellysweep"
