name: pre-commit

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  pre-commit:
    if: github.event.action != 'labeled' || github.event.label.name == 'pre-commit ci run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Remove pre-commit ci run label
        if: github.event.action == 'labeled' && github.event.label.name == 'pre-commit ci run'
        run: gh pr edit ${{ github.event.number }} --remove-label 'pre-commit ci run'
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Go tools
        run: |
          go get -tool github.com/a-h/templ/cmd/templ@latest
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.1

      - name: Install gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: pre-commit ci lite
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
