name: Update pre-commit hooks

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-hooks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks
        run: pre-commit autoupdate

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet .pre-commit-config.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: |
            This is an automated pull request to update pre-commit hook versions.

            ## Changes
            - Updated pre-commit hook versions to their latest releases

            ## Testing
            The pre-commit workflow will automatically run on this PR to validate the changes.

            Auto-generated by the weekly pre-commit update workflow.
          branch: update-pre-commit-hooks
          delete-branch: true
          labels: |
            dependencies
            pre-commit
