// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/jon4hz/jellysweep/api/models"
import "fmt"

// AdminKeepRequestGrid creates a media grid specifically for keep requests in admin panel
func AdminKeepRequestGrid(keepRequests []models.KeepRequest) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"approval-queue-container\" class=\"space-y-4\"><!-- Loading State --><div id=\"approval-queue-container-grid-loading\" class=\"hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SkeletonGrid(8).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><!-- Custom content (filters, search, etc.) -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AdminKeepRequestFilters(keepRequests).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Media Grid --><div id=\"approval-queue-grid\" class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-4 sm:gap-6 transition-opacity duration-200\" data-page-size=\"8\" data-mobile-page-size=\"4\" data-total-items=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(len(keepRequests)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 21, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-enable-search=\"true\" data-enable-filters=\"true\" data-enable-sorting=\"true\" data-enable-refresh=\"true\" data-animate-changes=\"true\" data-keep-requests=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.JSONString(keepRequests))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 27, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><!-- Items will be populated by JavaScript --></div><!-- Loading indicator for infinite scroll --><div id=\"approval-queue-container-scroll-loading\" class=\"hidden text-center py-8\"><div class=\"inline-flex items-center space-x-2\"><div class=\"animate-spin rounded-full h-6 w-6 border-b-2 border-indigo-500\"></div><span class=\"text-gray-400\">Loading more...</span></div></div><!-- Load More Button (fallback for poor connections) --><div id=\"approval-queue-container-load-more-container\" class=\"text-center mt-6 hidden\"><button id=\"approval-queue-container-load-more-btn\" class=\"btn-secondary\"><svg class=\"w-4 h-4 mr-2\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 6v6m0 0v6m0-6h6m-6 0H6\"></path></svg> Load More</button></div><!-- Scroll to Top Button --><button id=\"approval-queue-container-scroll-to-top\" class=\"fixed bottom-4 right-4 md:bottom-6 md:right-6 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white p-2 md:p-3 rounded-full shadow-lg transition-all duration-200 opacity-0 pointer-events-none z-50 transform translate-y-4\" aria-label=\"Scroll to top\"><svg class=\"w-4 h-4 md:w-5 md:h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 10l7-7m0 0l7 7m-7-7v18\"></path></svg></button><!-- Virtual scroll sentinel for intersection observer --><div id=\"approval-queue-container-scroll-sentinel\" class=\"h-1 opacity-0\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// AdminKeepRequestFilters creates the filter interface for keep requests
func AdminKeepRequestFilters(keepRequests []models.KeepRequest) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"card-no-hover p-4 sm:p-6 mb-6\"><div class=\"flex flex-col space-y-4 lg:space-y-0 lg:flex-row lg:items-center lg:justify-between\"><div class=\"flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4\"><div class=\"relative flex-1 sm:flex-none\"><input type=\"text\" id=\"request-search\" placeholder=\"Search keep requests...\" class=\"input-field pl-10 pr-4 py-2 w-full sm:w-64\"><div class=\"absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none\"><svg class=\"h-5 w-5 text-gray-400\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\"></path></svg></div></div><select id=\"request-library-filter\" class=\"input-field flex-1 sm:flex-none\"><option value=\"\">All Libraries</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, library := range getUniqueKeepRequestLibraries(keepRequests) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(library)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 78, Col: 29}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(library)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 78, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</select> <select id=\"request-type-filter\" class=\"input-field flex-1 sm:flex-none\"><option value=\"\">All Types</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, mediaType := range getUniqueKeepRequestTypes(keepRequests) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(mediaType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 84, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(mediaType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 84, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</select> <select id=\"request-sort-by\" class=\"input-field flex-1 sm:flex-none\"><option value=\"expiry-date-asc\">Expires Soonest First</option> <option value=\"expiry-date-desc\">Expires Latest First</option> <option value=\"deletion-date-asc\">Deletion Date (Earliest First)</option> <option value=\"deletion-date-desc\">Deletion Date (Latest First)</option> <option value=\"title-asc\">Title (A-Z)</option> <option value=\"title-desc\">Title (Z-A)</option></select></div><div class=\"flex items-center\"><button id=\"request-refresh-btn\" class=\"flex items-center justify-center btn-secondary w-full sm:w-auto\"><svg class=\"w-4 h-4 mr-2\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg> Refresh</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// AdminMediaGrid creates a media grid for keep/sweep decisions in admin panel
func AdminMediaGrid(mediaItems []models.MediaItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = MediaGrid(mediaItems, MediaGridConfig{
			ContainerID:    "keep-sweep-container",
			GridID:         "keep-sweep-grid",
			EnableSearch:   true,
			EnableFilters:  true,
			EnableSorting:  true,
			EnableRefresh:  true,
			PageSize:       8,
			MobilePageSize: 4,
			AnimateChanges: true,
		}, AdminMediaFilters(mediaItems)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// AdminMediaFilters creates the filter interface for keep/sweep media
func AdminMediaFilters(mediaItems []models.MediaItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"card-no-hover p-4 sm:p-6 mb-6\"><div class=\"flex flex-col space-y-4 lg:space-y-0 lg:flex-row lg:items-center lg:justify-between\"><div class=\"flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4\"><div class=\"relative flex-1 sm:flex-none\"><input type=\"text\" id=\"media-search\" placeholder=\"Search media...\" class=\"input-field pl-10 pr-4 py-2 w-full sm:w-64\"><div class=\"absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none\"><svg class=\"h-5 w-5 text-gray-400\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\"></path></svg></div></div><select id=\"media-library-filter\" class=\"input-field flex-1 sm:flex-none\"><option value=\"\">All Libraries</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, library := range GetUniqueLibraries(mediaItems) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(library)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 139, Col: 29}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(library)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 139, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</select> <select id=\"media-type-filter\" class=\"input-field flex-1 sm:flex-none\"><option value=\"\">All Types</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, mediaType := range getUniqueMediaTypes(mediaItems) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(mediaType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 145, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(mediaType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/admin-media-grid.templ`, Line: 145, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</select> <select id=\"media-status-filter\" class=\"input-field flex-1 sm:flex-none\"><option value=\"\">All Status</option> <option value=\"requested\">Keep Requested</option> <option value=\"must-delete\">Must Delete</option> <option value=\"normal\">Normal</option></select> <select id=\"media-sort-by\" class=\"input-field flex-1 sm:flex-none\"><option value=\"deletion-date-asc\">Deletion Date (Earliest First)</option> <option value=\"deletion-date-desc\">Deletion Date (Latest First)</option> <option value=\"title-asc\">Title (A-Z)</option> <option value=\"title-desc\">Title (Z-A)</option> <option value=\"size-asc\">File Size (Smallest First)</option> <option value=\"size-desc\">File Size (Largest First)</option></select></div><div class=\"flex items-center\"><button id=\"media-refresh-btn\" class=\"flex items-center justify-center btn-secondary w-full sm:w-auto\"><svg class=\"w-4 h-4 mr-2\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg> Refresh</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Helper functions to extract unique values for filters
func getUniqueKeepRequestLibraries(requests []models.KeepRequest) []string {
	libraryMap := make(map[string]bool)
	var libraries []string

	for _, request := range requests {
		if request.Library != "" && !libraryMap[request.Library] {
			libraryMap[request.Library] = true
			libraries = append(libraries, request.Library)
		}
	}

	return libraries
}

func getUniqueKeepRequestTypes(requests []models.KeepRequest) []models.MediaType {
	typeMap := make(map[models.MediaType]bool)
	var types []models.MediaType

	for _, request := range requests {
		if request.Type != "" && !typeMap[request.Type] {
			typeMap[request.Type] = true
			types = append(types, request.Type)
		}
	}

	return types
}

func getUniqueMediaTypes(items []models.MediaItem) []models.MediaType {
	typeMap := make(map[models.MediaType]bool)
	var types []models.MediaType

	for _, item := range items {
		if item.Type != "" && !typeMap[item.Type] {
			typeMap[item.Type] = true
			types = append(types, item.Type)
		}
	}

	return types
}

// Convert KeepRequest to MediaItem for compatibility with MediaGrid
func convertKeepRequestsToMediaItems(requests []models.KeepRequest) []models.MediaItem {
	items := make([]models.MediaItem, len(requests))

	for i, request := range requests {
		items[i] = models.MediaItem{
			ID:           request.MediaID,
			Title:        request.Title,
			Type:         request.Type,
			Year:         int32(request.Year),
			Library:      request.Library,
			PosterURL:    request.PosterURL,
			DeletionDate: request.DeletionDate,
			FileSize:     0,     // KeepRequest doesn't have file size
			HasRequested: true,  // By definition, all keep requests have been requested
			CanRequest:   false, // Already requested
			MustDelete:   false, // Keep requests are for keeping
			CleanupMode:  "",
			KeepCount:    0,
		}
	}

	return items
}

func AdminKeepRequestGridScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AdminKeepRequestGridScript_a913`,
		Function: `function __templ_AdminKeepRequestGridScript_a913(){class AdminKeepRequestGridManager extends MediaGridManager {
		constructor(containerId, options = {}) {
			super(containerId, options);
			// Store original keep requests data for expiry information
			this.keepRequestsData = {};
		}

		loadMediaItemsFromDOM() {
			// Add a small delay to ensure DOM and data attributes are fully ready
			setTimeout(() => {
				this.doLoadMediaItemsFromDOM();
			}, 0);
		}

		doLoadMediaItemsFromDOM() {
			try {
				// Ensure the grid element exists and has data
				if (!this.grid) {
					console.warn('Grid element not found, retrying...');
					setTimeout(() => this.doLoadMediaItemsFromDOM(), 50);
					return;
				}

				const keepRequestsData = this.grid.dataset.keepRequests;
				if (!keepRequestsData) {
					console.warn('No keep requests data found in grid element, retrying...');
					// Retry a few times in case the data attribute is still being set
					if (!this.retryCount) this.retryCount = 0;
					if (this.retryCount < 5) {
						this.retryCount++;
						setTimeout(() => this.doLoadMediaItemsFromDOM(), 100);
						return;
					}
					console.warn('Failed to load keep requests data after retries');
					this.setItems([]);
					return;
				}

				const rawKeepRequests = JSON.parse(keepRequestsData);
				// Transform KeepRequest to MediaItem format for the grid
				const transformedItems = rawKeepRequests.map(request => {

					const deletionTimestamp = request.DeletionDate ? new Date(request.DeletionDate).getTime() : 0;

					return {
						id: request.MediaID,
						title: request.Title,
						type: request.Type,
						year: request.Year,
						library: request.Library,
						posterURL: request.PosterURL,
						deletionTimestamp: deletionTimestamp,
						expiryTimestamp: request.ExpiryDate ? new Date(request.ExpiryDate).getTime() : Date.now() + (7 * 24 * 60 * 60 * 1000),
						canRequest: false, // Already requested
						hasRequested: true, // By definition
						mustDelete: false, // Keep requests are for keeping
						fileSize: 0,
						cleanupMode: "",
						keepCount: 0
					};
				});
				this.setItems(transformedItems);
			} catch (error) {
				console.error('Failed to parse keep requests data:', error);
				this.setItems([]);
			}
		}

		createCardElement(item) {
			const div = document.createElement('div');
			div.className = 'media-card';
			div.id = ` + "`" + `request-${item.id}` + "`" + `;
			div.setAttribute('data-media-id', item.id);
			div.setAttribute('data-item-id', item.id);
			div.setAttribute('data-title', item.title);
			div.setAttribute('data-library', item.library);
			div.setAttribute('data-type', item.type);
			div.setAttribute('data-expiry-timestamp', item.expiryTimestamp || 0);

			// Use the admin-specific card HTML for keep requests
			div.innerHTML = this.createKeepRequestCardHTML(item);

			// Use event delegation on the card div instead of finding individual buttons
			div.addEventListener('click', (e) => {
				e.preventDefault();
				const target = e.target.closest('button');
				if (!target) return;

				const mediaId = target.getAttribute('data-media-id');
				if (mediaId !== item.id) return;

				if (target.classList.contains('accept-btn')) {
					const originalContent = this.setButtonLoading(target, 'Accepting...');
					this.handleItemAction(item.id, 'accept', div).catch(() => {
						this.resetButton(target, originalContent);
					});
				} else if (target.classList.contains('decline-btn')) {
					const originalContent = this.setButtonLoading(target, 'Declining...');
					this.handleItemAction(item.id, 'decline', div).catch(() => {
						this.resetButton(target, originalContent);
					});
				}
			});

			return div;
		}

		createKeepRequestCardHTML(item) {
			// Note: For keep requests, we don't have file size, so we'll omit it
			const deletionDate = new Date(item.deletionTimestamp);
			const deletionTime = this.formatRelativeTime(deletionDate);

			// For keep requests, we need to handle expiry date
			const expiryDate = new Date(item.expiryTimestamp || Date.now() + 7*24*60*60*1000); // Default to 7 days if not set
			const expiryTime = this.formatRelativeTime(expiryDate);

			const posterImg = item.posterURL
				? ` + "`" + `<img src="${item.posterURL}" class="w-full h-64 object-cover" loading="lazy"/>` + "`" + `
				: ` + "`" + `<div class="w-full h-64 bg-gray-700 flex items-center justify-center">
					<svg class="w-16 h-16 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4V2a1 1 0 011-1h8a1 1 0 011 1v2h3a1 1 0 011 1v2a1 1 0 01-1 1h-1v12a2 2 0 01-2 2H6a2 2 0 01-2-2V8H3a1 1 0 01-1-1V5a1 1 0 011-1h3z"></path>
					</svg>
				</div>` + "`" + `;

			return ` + "`" + `
				<!-- Desktop Card Layout -->
				<div class="hidden sm:block">
					<div class="card h-full flex flex-col">
						<div class="aspect-w-2 aspect-h-3 bg-gray-800 overflow-hidden rounded-t-lg">
							${posterImg}
						</div>
						<div class="p-4 flex-1 flex flex-col">
							<div class="flex-1">
								<h3 class="text-lg font-semibold text-gray-100 truncate">${item.title}</h3>
								<div class="flex items-center space-x-2 mt-1">
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										${item.type}
									</span>
									${item.year > 0 ? ` + "`" + `<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-600 text-gray-300">${item.year}</span>` + "`" + ` : ''}
								</div>
								<div class="mt-3 space-y-2">
									<div class="flex items-center text-sm text-gray-400">
										<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
										</svg>
										${item.library}
									</div>
									<div class="flex items-center text-sm text-red-400">
										<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Deletes ${deletionTime}
									</div>
									<div class="flex items-center text-sm text-yellow-400">
										<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3a4 4 0 118 0v4M5 7h14l-1 14H6L5 7z"></path>
										</svg>
										Expires ${expiryTime}
									</div>
								</div>
							</div>
							<div class="mt-4 flex gap-2">
								<button
									id="accept-desktop-${item.id}"
									data-media-id="${item.id}"
									class="admin-action-btn accept-btn flex-1 inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
									style="background-color: #16a34a; color: white;"
									onmouseover="this.style.backgroundColor='#15803d'"
									onmouseout="this.style.backgroundColor='#16a34a'"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
									</svg>
									Accept
								</button>
								<button
									id="decline-desktop-${item.id}"
									data-media-id="${item.id}"
									class="admin-action-btn decline-btn flex-1 inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
									style="background-color: #dc2626; color: white;"
									onmouseover="this.style.backgroundColor='#b91c1c'"
									onmouseout="this.style.backgroundColor='#dc2626'"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
									</svg>
									Decline
								</button>
							</div>
						</div>
					</div>
				</div>

				<!-- Mobile Horizontal Layout -->
				<div class="block sm:hidden">
					<div class="card">
						<div class="flex items-center p-4 gap-4">
							<div class="shrink-0">
								${item.posterURL
									? ` + "`" + `<img src="${item.posterURL}" alt="${item.title}" class="w-16 h-24 object-cover rounded" loading="lazy"/>` + "`" + `
									: ` + "`" + `<div class="w-16 h-24 bg-gray-700 rounded flex items-center justify-center">
										<svg class="w-8 h-8 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4V2a1 1 0 011-1h8a1 1 0 011 1v2h3a1 1 0 011 1v2a1 1 0 01-1 1h-1v12a2 2 0 01-2 2H6a2 2 0 01-2-2V8H3a1 1 0 01-1-1V5a1 1 0 011-1h3z"></path>
										</svg>
									</div>` + "`" + `
								}
							</div>
							<div class="flex-1 min-w-0">
								<h4 class="text-lg font-medium text-gray-100 truncate">${item.title}</h4>
								<div class="mt-1 flex flex-wrap items-center gap-2 text-sm text-gray-400">
									<div class="flex items-center">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
										</svg>
										${item.library}
									</div>
									<div class="flex items-center text-red-400">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Deletes ${deletionTime}
									</div>
									<div class="flex items-center text-yellow-400">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3a4 4 0 118 0v4M5 7h14l-1 14H6L5 7z"></path>
										</svg>
										Expires ${expiryTime}
									</div>
								</div>
								<div class="mt-2 flex flex-wrap items-center gap-2">
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										${item.type}
									</span>
									${item.year > 0 ? ` + "`" + `<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-600 text-gray-300">${item.year}</span>` + "`" + ` : ''}
								</div>
								<div class="mt-3 flex gap-2">
									<button
										id="accept-mobile-${item.id}"
										data-media-id="${item.id}"
										class="admin-action-btn accept-btn flex-1 inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
										style="background-color: #16a34a; color: white;"
										onmouseover="this.style.backgroundColor='#15803d'"
										onmouseout="this.style.backgroundColor='#16a34a'"
									>
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
										</svg>
										Accept
									</button>
									<button
										id="decline-mobile-${item.id}"
										data-media-id="${item.id}"
										class="admin-action-btn decline-btn flex-1 inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
										style="background-color: #dc2626; color: white;"
										onmouseover="this.style.backgroundColor='#b91c1c'"
										onmouseout="this.style.backgroundColor='#dc2626'"
									>
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
										</svg>
										Decline
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			` + "`" + `;
		}

		// Override sorting to include expiry date
		sortItems(sortBy) {
			// Store current scroll position
			const scrollPosition = window.scrollY;

			this.filteredItems.sort((a, b) => {
				switch (sortBy) {
					case 'title-asc':
						return a.title.localeCompare(b.title);
					case 'title-desc':
						return b.title.localeCompare(a.title);
					case 'expiry-date-asc':
						return (a.expiryTimestamp || 0) - (b.expiryTimestamp || 0);
					case 'expiry-date-desc':
						return (b.expiryTimestamp || 0) - (a.expiryTimestamp || 0);
					case 'deletion-date-asc':
						return a.deletionTimestamp - b.deletionTimestamp;
					case 'deletion-date-desc':
						return b.deletionTimestamp - a.deletionTimestamp;
					default:
						return 0;
				}
			});

			// Re-render everything
			this.renderedItems.clear();
			this.hasMoreData = true;
			this.clearGrid();
			this.renderInitialBatch();

			// Restore scroll position smoothly
			requestAnimationFrame(() => {
				window.scrollTo({
					top: Math.min(scrollPosition, document.body.scrollHeight - window.innerHeight),
					behavior: 'smooth'
				});
			});
		}

		// Override filtering to include type filter
		filterItems(searchTerm, libraryFilter, typeFilter) {
			// Clear current state
			this.renderedItems.clear();
			this.currentPage = 1;
			this.hasMoreData = true;

			// Apply filters
			this.filteredItems = this.allItems.filter(item => {
				const matchesSearch = !searchTerm ||
					item.title.toLowerCase().includes(searchTerm.toLowerCase());
				const matchesLibrary = !libraryFilter || item.library === libraryFilter;
				const matchesType = !typeFilter || item.type === typeFilter;
				return matchesSearch && matchesLibrary && matchesType;
			});

			// Re-render with new filtered data
			this.clearGrid();
			this.renderInitialBatch();

			// Update has more data status
			this.hasMoreData = this.filteredItems.length > this.batchSize;
		}

		setupSearch() {
			const searchInput = document.getElementById('request-search');
			const libraryFilter = document.getElementById('request-library-filter');
			const typeFilter = document.getElementById('request-type-filter');
			const sortSelect = document.getElementById('request-sort-by');

			if (this.options.enableSearch && searchInput) {
				let searchTimeout;
				searchInput.addEventListener('input', (e) => {
					clearTimeout(searchTimeout);
					searchTimeout = setTimeout(() => {
						this.handleFilters();
					}, 300); // Debounce search
				});
			}

			if (this.options.enableFilters && libraryFilter) {
				libraryFilter.addEventListener('change', () => this.handleFilters());
			}

			if (typeFilter) {
				typeFilter.addEventListener('change', () => this.handleFilters());
			}

			if (this.options.enableSorting && sortSelect) {
				sortSelect.addEventListener('change', (e) => this.sortItems(e.target.value));
			}
		}

		handleFilters() {
			const searchTerm = this.options.enableSearch ? (document.getElementById('request-search')?.value || '') : '';
			const libraryFilter = this.options.enableFilters ? (document.getElementById('request-library-filter')?.value || '') : '';
			const typeFilter = document.getElementById('request-type-filter')?.value || '';
			this.filterItems(searchTerm, libraryFilter, typeFilter);
		}

		// Admin action handlers for keep requests
		handleItemAction(mediaId, action, cardElement) {
			if (!cardElement) {
				console.warn('No card element provided for action:', action);
				return Promise.resolve();
			}

			// Use direct API calls instead of global functions to avoid button ID conflicts
			let apiPromise;
			switch (action) {
				case 'accept':
					apiPromise = window.makeApiRequestEnhanced(` + "`" + `/admin/api/keep-requests/${mediaId}/accept` + "`" + `, {
						method: 'POST',
						showProgress: true
					});
					break;
				case 'decline':
					apiPromise = window.makeApiRequestEnhanced(` + "`" + `/admin/api/keep-requests/${mediaId}/decline` + "`" + `, {
						method: 'POST',
						showProgress: true
					});
					break;
				default:
					console.warn('Unknown action:', action);
					return Promise.resolve();
			}

			return apiPromise.then(data => {
				if (data && data.success) {
					// Show success toast and update pending count
					if (window.showToast) {
						const actionText = action === 'accept' ? 'accepted' : 'declined';
						window.showToast(` + "`" + `Keep request ${actionText} successfully` + "`" + `, 'success');
					}
					if (window.updatePendingCount) {
						window.updatePendingCount(-1);
					}

					// Use the base class removeItem method which handles both data removal and animation
					const animationType = action === 'accept' ? 'swipe-right' : 'swipe-left';
					return this.removeItem(mediaId, animationType);
				} else {
					throw new Error(data?.error || 'Unknown error');
				}
			}).catch(error => {
				console.error('Action failed:', error);
				if (window.showToast) {
					window.showToast(` + "`" + `Failed to ${action} request: ${error.message}` + "`" + `, 'error');
				}
				// Don't remove the card if the API call failed
				throw error;
			});
		}

		// Set button to loading state using global function
		setButtonLoading(button, loadingText) {
			if (!button) return null;

			// Ensure button has an ID for the global function
			if (!button.id) {
				button.id = 'btn-' + Math.random().toString(36).substr(2, 9);
			}

			// Use global setButtonLoading function
			return window.setButtonLoading(button.id, loadingText);
		}

		// Reset button using global function
		resetButton(button, originalContent) {
			if (!button || !button.id) return;

			// Use global restoreButton function
			window.restoreButton(button.id, originalContent);
		}

		formatRelativeTime(date) {
			const now = new Date();
			const diffInMs = date.getTime() - now.getTime();
			const diffInDays = Math.ceil(diffInMs / (1000 * 60 * 60 * 24));

			if (diffInDays === 0) return 'today';
			if (diffInDays === 1) return 'tomorrow';
			if (diffInDays > 1) return ` + "`" + `in ${diffInDays} days` + "`" + `;
			if (diffInDays === -1) return 'yesterday';
			return ` + "`" + `${Math.abs(diffInDays)} days ago` + "`" + `;
		}

		// Override setItems to handle keep request data format
		setItems(keepRequests) {
			// Transform KeepRequest objects to MediaItem format
			const transformedItems = keepRequests.map(request => {
				// Check if data is already in client format (has deletionTimestamp)
				// vs server format (has DeletionDate)
				let deletionTimestamp;
				if (request.deletionTimestamp !== undefined) {
					// Already in client format, use as-is
					deletionTimestamp = request.deletionTimestamp;
				} else if (request.DeletionDate) {
					// Server format, convert to timestamp
					deletionTimestamp = new Date(request.DeletionDate).getTime();
				} else {
					// No deletion date available
					deletionTimestamp = 0;
				}

				let expiryTimestamp;
				if (request.expiryTimestamp !== undefined) {
					// Already in client format, use as-is
					expiryTimestamp = request.expiryTimestamp;
				} else if (request.ExpiryDate) {
					// Server format, convert to timestamp
					expiryTimestamp = new Date(request.ExpiryDate).getTime();
				} else {
					// Default expiry (7 days from now)
					expiryTimestamp = Date.now() + (7 * 24 * 60 * 60 * 1000);
				}

				return {
					id: request.MediaID || request.id,
					title: request.Title || request.title,
					type: request.Type || request.type,
					year: request.Year || request.year,
					library: request.Library || request.library,
					posterURL: request.PosterURL || request.posterURL,
					deletionTimestamp: deletionTimestamp,
					expiryTimestamp: expiryTimestamp,
					canRequest: false,
					hasRequested: true,
					mustDelete: false,
					fileSize: 0,
					cleanupMode: "",
					keepCount: 0
				};
			});

			// Call parent setItems with transformed data
			this.allItems = transformedItems || [];
			this.filteredItems = [...this.allItems];
			this.renderedItems.clear();
			this.currentPage = 1;
			this.hasMoreData = this.filteredItems.length > this.batchSize;

			// Clear grid and render initial batch (handleFilters will call renderInitialBatch too)
			this.clearGrid();
			this.renderInitialBatch();
		}

		// Refresh method to update grid with current data
		refresh() {
			this.clearGrid();
			this.currentPage = 1;
			this.hasMoreData = true;

			setTimeout(() => {
				this.renderInitialBatch();
			}, 0);

			this.hasMoreData = this.filteredItems.length > this.batchSize;
		}
	}

	// Export for admin use
	window.AdminKeepRequestGridManager = AdminKeepRequestGridManager;

	// Initialize admin keep request grid when DOM loads
	document.addEventListener('DOMContentLoaded', function() {
		if (document.getElementById('approval-queue-container')) {
			window.adminKeepRequestGridManager = new AdminKeepRequestGridManager('approval-queue-container', {
				gridId: 'approval-queue-grid',
				enableSearch: true,
				enableFilters: true,
				enableSorting: true,
				enableRefresh: true,
				pageSize: 10,
				mobilePageSize: 4,
				animateChanges: true
			});
		}
	});
}`,
		Call:       templ.SafeScript(`__templ_AdminKeepRequestGridScript_a913`),
		CallInline: templ.SafeScriptInline(`__templ_AdminKeepRequestGridScript_a913`),
	}
}

func AdminMediaGridScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AdminMediaGridScript_11e6`,
		Function: `function __templ_AdminMediaGridScript_11e6(){class AdminMediaGridManager extends MediaGridManager {
		constructor(containerId, options = {}) {
			super(containerId, options);
		}

		loadMediaItemsFromDOM() {
			// Add a small delay to ensure DOM and data attributes are fully ready
			setTimeout(() => {
				this.doLoadMediaItemsFromDOM();
			}, 0);
		}

		doLoadMediaItemsFromDOM() {
			try {
				// Ensure the grid element exists and has data
				if (!this.grid) {
					console.warn('Grid element not found, retrying...');
					setTimeout(() => this.doLoadMediaItemsFromDOM(), 50);
					return;
				}

				const mediaItemsData = this.grid.dataset.mediaItems;
				if (!mediaItemsData) {
					console.warn('No media items data found in grid element, retrying...');
					// Retry a few times in case the data attribute is still being set
					if (!this.retryCount) this.retryCount = 0;
					if (this.retryCount < 5) {
						this.retryCount++;
						setTimeout(() => this.doLoadMediaItemsFromDOM(), 100);
						return;
					}
					console.warn('Failed to load media items data after retries');
					this.setItems([]);
					return;
				}

				const rawMediaItems = JSON.parse(mediaItemsData);
				// Transform Go struct field names to JavaScript-friendly names
				const transformedItems = rawMediaItems.map(item => ({
					id: item.ID,
					title: item.Title,
					type: item.Type,
					year: item.Year,
					library: item.Library,
					posterURL: item.PosterURL,
					deletionTimestamp: item.DeletionDate ? new Date(item.DeletionDate).getTime() : 0,
					fileSize: item.FileSize || 0,
					hasRequested: item.HasRequested || false,
					canRequest: item.CanRequest !== false, // Default to true unless explicitly false
					mustDelete: item.MustDelete || false,
					cleanupMode: item.CleanupMode || "",
					keepCount: item.KeepCount || 0
				}));
				this.setItems(transformedItems);
			} catch (error) {
				console.error('Failed to parse media items data:', error);
				this.setItems([]);
			}
		}

		createCardElement(item) {
			const div = document.createElement('div');
			div.className = 'media-card';
			div.id = ` + "`" + `media-${item.id}` + "`" + `;
			div.setAttribute('data-media-id', item.id);
			div.setAttribute('data-item-id', item.id);
			div.setAttribute('data-title', item.title);
			div.setAttribute('data-library', item.library);
			div.setAttribute('data-type', item.type);
			div.setAttribute('data-status', this.getItemStatus(item));

			// Use the admin-specific card HTML for media items
			div.innerHTML = this.createAdminMediaCardHTML(item);

			// Use event delegation on the card div instead of finding individual buttons
			div.addEventListener('click', (e) => {
				e.preventDefault();
				const target = e.target.closest('button');
				if (!target) return;

				const mediaId = target.getAttribute('data-media-id');
				if (mediaId !== item.id) return;

				if (target.classList.contains('keep-btn')) {
					const originalContent = this.setButtonLoading(target, 'Keeping...');
					this.handleItemAction(item.id, 'keep', div).catch(() => {
						this.resetButton(target, originalContent);
					});
				} else if (target.classList.contains('keep-forever-btn')) {
					const originalContent = this.setButtonLoading(target, 'Keeping...');
					this.handleItemAction(item.id, 'keep-forever', div).catch(() => {
						this.resetButton(target, originalContent);
					});
				} else if (target.classList.contains('delete-btn')) {
					const originalContent = this.setButtonLoading(target, 'Sweeping...');
					this.handleItemAction(item.id, 'sweep', div).catch(() => {
						this.resetButton(target, originalContent);
					});
				}
			});

			return div;
		}

		getItemStatus(item) {
			if (item.hasRequested) return 'requested';
			if (item.mustDelete) return 'must-delete';
			return 'normal';
		}

		createAdminMediaCardHTML(item) {
			const formattedSize = this.formatFileSize(item.fileSize);
			const deletionDate = new Date(item.deletionTimestamp);
			const relativeTime = this.formatRelativeTime(deletionDate);

			const posterImg = item.posterURL
				? ` + "`" + `<img src="${item.posterURL}" class="w-full h-64 object-cover" loading="lazy"/>` + "`" + `
				: ` + "`" + `<div class="w-full h-64 bg-gray-700 flex items-center justify-center">
					<svg class="w-16 h-16 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4V2a1 1 0 011-1h8a1 1 0 011 1v2h3a1 1 0 011 1v2a1 1 0 01-1 1h-1v12a2 2 0 01-2 2H6a2 2 0 01-2-2V8H3a1 1 0 01-1-1V5a1 1 0 011-1h3z"></path>
					</svg>
				</div>` + "`" + `;

			return ` + "`" + `
				<!-- Desktop Card Layout -->
				<div class="hidden sm:block">
					<div class="card h-full flex flex-col">
						<div class="aspect-w-2 aspect-h-3 bg-gray-800 overflow-hidden rounded-t-lg">
							${posterImg}
						</div>
						<div class="p-4 flex-1 flex flex-col">
							<div class="flex-1">
								<h3 class="text-lg font-semibold text-gray-100 truncate">${item.title}</h3>
								<div class="flex items-center space-x-2 mt-1">
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										${item.type}
									</span>
									${item.year > 0 ? ` + "`" + `<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-600 text-gray-300">${item.year}</span>` + "`" + ` : ''}
								</div>
								<div class="mt-3 space-y-2">
									<div class="flex flex-wrap items-center gap-2 text-sm text-gray-400">
										<div class="flex items-center">
											<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
											</svg>
											${item.library}
										</div>
										<div class="flex items-center">
											<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
											</svg>
											${formattedSize}
										</div>
									</div>
									<div class="flex items-center text-sm text-red-400">
										<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Deletes ${relativeTime}
									</div>
								</div>
								<div class="mt-3 flex flex-wrap items-center gap-2">
									${item.hasRequested ? ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-yellow-900 text-yellow-200">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Keep Requested
									</span>
									` + "`" + ` : item.mustDelete ? ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-red-900 text-red-200">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
										</svg>
										Must Delete
									</span>
									` + "`" + ` : ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										No Request
									</span>
									` + "`" + `}
								</div>
							</div>
							<div class="mt-4 flex flex-col gap-2">
								<button
									id="keep-desktop-${item.id}"
									data-media-id="${item.id}"
									class="admin-action-btn keep-btn w-full inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
									style="background-color: #16a34a; color: white;"
									onmouseover="this.style.backgroundColor='#15803d'"
									onmouseout="this.style.backgroundColor='#16a34a'"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
									</svg>
									Keep
								</button>
								<button
									id="keep-forever-desktop-${item.id}"
									data-media-id="${item.id}"
									class="admin-action-btn keep-forever-btn w-full inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
									style="background-color: #4f46e5; color: white;"
									onmouseover="this.style.backgroundColor='#3730a3'"
									onmouseout="this.style.backgroundColor='#4f46e5'"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path>
									</svg>
									Keep Forever
								</button>
								<button
									id="delete-desktop-${item.id}"
									data-media-id="${item.id}"
									class="admin-action-btn delete-btn w-full inline-flex items-center justify-center px-3 py-2 rounded-lg font-medium transition-colors duration-200 text-sm"
									style="background-color: #dc2626; color: white;"
									onmouseover="this.style.backgroundColor='#b91c1c'"
									onmouseout="this.style.backgroundColor='#dc2626'"
								>
									<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
									</svg>
									Sweep
								</button>
							</div>
						</div>
					</div>
				</div>

				<!-- Mobile Horizontal Layout -->
				<div class="block sm:hidden">
					<div class="card">
						<div class="flex items-center p-4 gap-4">
							<div class="shrink-0">
								${item.posterURL
									? ` + "`" + `<img src="${item.posterURL}" alt="${item.title}" class="w-16 h-24 object-cover rounded" loading="lazy"/>` + "`" + `
									: ` + "`" + `<div class="w-16 h-24 bg-gray-700 rounded flex items-center justify-center">
										<svg class="w-8 h-8 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4V2a1 1 0 011-1h8a1 1 0 011 1v2h3a1 1 0 011 1v2a1 1 0 01-1 1h-1v12a2 2 0 01-2 2H6a2 2 0 01-2-2V8H3a1 1 0 01-1-1V5a1 1 0 011-1h3z"></path>
										</svg>
									</div>` + "`" + `
								}
							</div>
							<div class="flex-1 min-w-0">
								<h4 class="text-lg font-medium text-gray-100 truncate">${item.title}</h4>
								<div class="mt-1 flex flex-wrap items-center gap-2 text-sm text-gray-400">
									<div class="flex items-center">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
										</svg>
										${item.library}
									</div>
									<div class="flex items-center">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
										</svg>
										${formattedSize}
									</div>
									<div class="flex items-center text-red-400">
										<svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Deletes ${relativeTime}
									</div>
								</div>
								<div class="mt-2 flex flex-wrap items-center gap-2">
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										${item.type}
									</span>
									${item.year > 0 ? ` + "`" + `<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-600 text-gray-300">${item.year}</span>` + "`" + ` : ''}
									${item.hasRequested ? ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-yellow-900 text-yellow-200">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										Keep Requested
									</span>
									` + "`" + ` : item.mustDelete ? ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-red-900 text-red-200">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
										</svg>
										Must Delete
									</span>
									` + "`" + ` : ` + "`" + `
									<span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-700 text-gray-300">
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
										</svg>
										No Request
									</span>
									` + "`" + `}
								</div>
								<div class="mt-3 flex gap-2">
									<button
										id="keep-mobile-${item.id}"
										data-media-id="${item.id}"
										class="admin-action-btn keep-btn flex-1 inline-flex items-center justify-center px-2 py-2 rounded-lg font-medium transition-colors duration-200 text-xs"
										style="background-color: #16a34a; color: white;"
										onmouseover="this.style.backgroundColor='#15803d'"
										onmouseout="this.style.backgroundColor='#16a34a'"
									>
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
										</svg>
										Keep
									</button>
									<button
										id="keep-forever-mobile-${item.id}"
										data-media-id="${item.id}"
										class="admin-action-btn keep-forever-btn flex-1 inline-flex items-center justify-center px-2 py-2 rounded-lg font-medium transition-colors duration-200 text-xs"
										style="background-color: #4f46e5; color: white;"
										onmouseover="this.style.backgroundColor='#3730a3'"
										onmouseout="this.style.backgroundColor='#4f46e5'"
									>
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path>
										</svg>
										Forever
									</button>
									<button
										id="delete-mobile-${item.id}"
										data-media-id="${item.id}"
										class="admin-action-btn delete-btn flex-1 inline-flex items-center justify-center px-2 py-2 rounded-lg font-medium transition-colors duration-200 text-xs"
										style="background-color: #dc2626; color: white;"
										onmouseover="this.style.backgroundColor='#b91c1c'"
										onmouseout="this.style.backgroundColor='#dc2626'"
									>
										<svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
										</svg>
										Sweep
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			` + "`" + `;
		}

		// Override filtering to include status filter
		filterItems(searchTerm, libraryFilter, typeFilter, statusFilter) {
			// Clear current state
			this.renderedItems.clear();
			this.currentPage = 1;
			this.hasMoreData = true;

			// Apply filters
			this.filteredItems = this.allItems.filter(item => {
				const matchesSearch = !searchTerm ||
					item.title.toLowerCase().includes(searchTerm.toLowerCase());
				const matchesLibrary = !libraryFilter || item.library === libraryFilter;
				const matchesType = !typeFilter || item.type === typeFilter;

				let matchesStatus = true;
				if (statusFilter) {
					switch (statusFilter) {
						case 'requested':
							matchesStatus = item.hasRequested;
							break;
						case 'must-delete':
							matchesStatus = item.mustDelete;
							break;
						case 'normal':
							matchesStatus = !item.hasRequested && !item.mustDelete;
							break;
					}
				}

				return matchesSearch && matchesLibrary && matchesType && matchesStatus;
			});

			// Re-render with new filtered data
			this.clearGrid();
			this.renderInitialBatch();

			// Update has more data status
			this.hasMoreData = this.filteredItems.length > this.batchSize;
		}

		setupSearch() {
			const searchInput = document.getElementById('media-search');
			const libraryFilter = document.getElementById('media-library-filter');
			const typeFilter = document.getElementById('media-type-filter');
			const statusFilter = document.getElementById('media-status-filter');
			const sortSelect = document.getElementById('media-sort-by');

			if (this.options.enableSearch && searchInput) {
				let searchTimeout;
				searchInput.addEventListener('input', (e) => {
					clearTimeout(searchTimeout);
					searchTimeout = setTimeout(() => {
						this.handleFilters();
					}, 300); // Debounce search
				});
			}

			if (this.options.enableFilters && libraryFilter) {
				libraryFilter.addEventListener('change', () => this.handleFilters());
			}

			if (typeFilter) {
				typeFilter.addEventListener('change', () => this.handleFilters());
			}

			if (statusFilter) {
				statusFilter.addEventListener('change', () => this.handleFilters());
			}

			if (this.options.enableSorting && sortSelect) {
				sortSelect.addEventListener('change', (e) => this.sortItems(e.target.value));
			}
		}

		handleFilters() {
			const searchTerm = this.options.enableSearch ? (document.getElementById('media-search')?.value || '') : '';
			const libraryFilter = this.options.enableFilters ? (document.getElementById('media-library-filter')?.value || '') : '';
			const typeFilter = document.getElementById('media-type-filter')?.value || '';
			const statusFilter = document.getElementById('media-status-filter')?.value || '';
			this.filterItems(searchTerm, libraryFilter, typeFilter, statusFilter);
		}

		// Admin action handlers for media items
		handleItemAction(mediaId, action, cardElement) {
			if (!cardElement) {
				console.warn('No card element provided for action:', action);
				return Promise.resolve();
			}

			// Use direct API calls instead of global functions to avoid button ID conflicts
			let apiPromise;
			switch (action) {
				case 'keep':
					apiPromise = window.makeApiRequest(` + "`" + `/admin/api/media/${mediaId}/keep` + "`" + `);
					break;
				case 'keep-forever':
					apiPromise = window.makeApiRequest(` + "`" + `/admin/api/media/${mediaId}/keep-forever` + "`" + `);
					break;
				case 'sweep':
					apiPromise = window.makeApiRequestEnhanced(` + "`" + `/admin/api/media/${mediaId}/delete` + "`" + `, {
						method: 'POST',
						showProgress: true
					});
					break;
				default:
					console.warn('Unknown action:', action);
					return Promise.resolve();
			}

			return apiPromise.then(data => {
				if (data && data.success) {
					// Show success toast
					const actionText = {
						'keep': 'marked as keep',
						'keep-forever': 'protected forever',
						'sweep': 'marked for deletion'
					}[action];
					if (window.showToast) {
						window.showToast(` + "`" + `Media ${actionText} successfully` + "`" + `, 'success');
					}

					// Use the base class removeItem method which handles both data removal and animation
					let animationType;
					switch (action) {
						case 'keep':
							animationType = 'swipe-right';
							break;
						case 'keep-forever':
							animationType = 'fly-up';
							break;
						case 'sweep':
							animationType = 'swipe-left';
							break;
						default:
							animationType = 'default';
					}
					return this.removeItem(mediaId, animationType);
				} else {
					throw new Error(data?.error || 'Unknown error');
				}
			}).catch(error => {
				console.error('Action failed:', error);
				if (window.showToast) {
					window.showToast(` + "`" + `Failed to ${action} media: ${error.message}` + "`" + `, 'error');
				}
				// Don't remove the card if the API call failed
				throw error;
			});
		}

		// Set button to loading state using global function
		setButtonLoading(button, loadingText) {
			if (!button) return null;

			// Ensure button has an ID for the global function
			if (!button.id) {
				button.id = 'btn-' + Math.random().toString(36).substr(2, 9);
			}

			// Use global setButtonLoading function
			return window.setButtonLoading(button.id, loadingText);
		}

		// Reset button using global function
		resetButton(button, originalContent) {
			if (!button || !button.id) return;

			// Use global restoreButton function
			window.restoreButton(button.id, originalContent);
		}

		formatFileSize(bytes) {
			if (bytes === 0) return '0 Bytes';
			const k = 1024;
			const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
			const i = Math.floor(Math.log(bytes) / Math.log(k));
			return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
		}

		formatRelativeTime(date) {
			const now = new Date();
			const diffInMs = date.getTime() - now.getTime();
			const diffInDays = Math.ceil(diffInMs / (1000 * 60 * 60 * 24));

			if (diffInDays === 0) return 'today';
			if (diffInDays === 1) return 'tomorrow';
			if (diffInDays > 1) return ` + "`" + `in ${diffInDays} days` + "`" + `;
			if (diffInDays === -1) return 'yesterday';
			return ` + "`" + `${Math.abs(diffInDays)} days ago` + "`" + `;
		}

		// Override setItems to handle media item data format
		setItems(mediaItems) {
			// Transform server data to client format
			const clientItems = mediaItems.map(item => {
				// Check if data is already in client format (has deletionTimestamp)
				// vs server format (has DeletionDate)
				let deletionTimestamp;
				if (item.deletionTimestamp !== undefined) {
					// Already in client format, use as-is
					deletionTimestamp = item.deletionTimestamp;
				} else if (item.DeletionDate) {
					// Server format, convert to timestamp
					deletionTimestamp = new Date(item.DeletionDate).getTime();
				} else {
					// No deletion date available
					deletionTimestamp = 0;
				}

				return {
					...item,
					id: item.ID || item.id,
					title: item.Title || item.title,
					library: item.Library || item.library,
					posterURL: item.PosterURL || item.posterURL,
					fileSize: parseInt(item.FileSize || item.fileSize || 0),
					deletionTimestamp: deletionTimestamp,
					hasRequested: item.HasRequested || item.hasRequested,
					canRequest: item.CanRequest !== undefined ? item.CanRequest : item.canRequest,
					mustDelete: item.MustDelete || item.mustDelete,
					cleanupMode: item.CleanupMode || item.cleanupMode,
					keepCount: parseInt(item.KeepCount || item.keepCount || 0),
					type: item.Type || item.type,
					year: parseInt(item.Year || item.year || 0)
				};
			});

			// Call parent setItems with transformed data
			this.allItems = clientItems || [];
			this.filteredItems = [...this.allItems];
			this.renderedItems.clear();
			this.currentPage = 1;
			this.hasMoreData = this.filteredItems.length > this.batchSize;

			// Clear grid and render initial batch (handleFilters will call renderInitialBatch too)
			this.clearGrid();
			this.renderInitialBatch();
		}

		// Refresh method to update grid with current data
		refresh() {
			this.clearGrid();
			this.currentPage = 1;
			this.hasMoreData = true;

			setTimeout(() => {
				this.renderInitialBatch();

			}, 0);

			this.hasMoreData = this.filteredItems.length > this.batchSize;
		}
	}

	// Export for admin use
	window.AdminMediaGridManager = AdminMediaGridManager;

	// Initialize admin media grid when DOM loads
	document.addEventListener('DOMContentLoaded', function() {
		if (document.getElementById('keep-sweep-container')) {
			window.adminMediaGridManager = new AdminMediaGridManager('keep-sweep-container', {
				gridId: 'keep-sweep-grid',
				enableSearch: true,
				enableFilters: true,
				enableSorting: true,
				enableRefresh: true,
				pageSize: 10,
				mobilePageSize: 4,
				animateChanges: true
			});
		}
	});
}`,
		Call:       templ.SafeScript(`__templ_AdminMediaGridScript_11e6`),
		CallInline: templ.SafeScriptInline(`__templ_AdminMediaGridScript_11e6`),
	}
}

var _ = templruntime.GeneratedTemplate
